export default [
  {
    "title": "第 1 类考点词",
    "define": "当其出现 90% 概率考察",
    "require": "滚瓜烂熟",
    "description": "核心高频考点词，必须熟练掌握词义、同义词及在真题中的命题方式。这些词汇在考试中出现频率最高，是提高阅读成绩的关键。",
    "words": [
      [
        1,
        "resemble",
        [
          "v."
        ],
        [
          "像，与……相似"
        ],
        [
          "like",
          "look",
          "be similar to"
        ],
        ""
      ],
      [
        2,
        "recognize",
        [
          "v."
        ],
        [
          "认出，识别；承认"
        ],
        [
          "perceive",
          "acknowledge",
          "realize",
          "appreciate",
          "admit",
          "identify",
          "comprehend",
          "understand",
          "know"
        ],
        ""
      ],
      [
        3,
        "adjust",
        [
          "v."
        ],
        [
          "调整，使适合"
        ],
        [
          "change",
          "modify",
          "shift",
          "alter"
        ],
        ""
      ],
      [
        4,
        "approach",
        [
          "n."
        ],
        [
          "方法"
        ],
        [
          "method",
          "way",
          "means"
        ],
        ""
      ],
      [
        5,
        "fundamental",
        [
          "adj."
        ],
        [
          "基本的，基础的"
        ],
        [
          "basic",
          "essential",
          "elementary",
          "primary"
        ],
        ""
      ],
      [
        6,
        "rely on",
        [
          "phr. v."
        ],
        [
          "依靠，依赖"
        ],
        [
          "depend on",
          "count on",
          "lean on"
        ],
        ""
      ],
      [
        7,
        "domestic",
        [
          "adj."
        ],
        [
          "家庭的；国内的"
        ],
        [
          "home",
          "local",
          "national"
        ],
        ""
      ],
      [
        8,
        "measure",
        [
          "v."
        ],
        [
          "测量"
        ],
        [
          "calculate",
          "assess",
          "evaluate",
          "gauge"
        ],
        ""
      ],
      [
        9,
        "trait",
        [
          "n."
        ],
        [
          "特性，特征"
        ],
        [
          "characteristic",
          "feature",
          "property",
          "attribute"
        ],
        ""
      ],
      [
        10,
        "coin",
        [
          "v."
        ],
        [
          "创造"
        ],
        [
          "invent",
          "devise",
          "formulate"
        ],
        ""
      ],
      [
        11,
        "artificial",
        [
          "adj."
        ],
        [
          "人造的，仿造的"
        ],
        [
          "synthetic",
          "man-made",
          "simulated"
        ],
        ""
      ],
      [
        12,
        "prompt",
        [
          "v."
        ],
        [
          "促进，激起"
        ],
        [
          "stimulate",
          "trigger",
          "initiate"
        ],
        ""
      ],
      [
        13,
        "exchange",
        [
          "v."
        ],
        [
          "交换"
        ],
        [
          "share",
          "swap",
          "trade",
          "interchange"
        ],
        ""
      ],
      [
        14,
        "underlie",
        [
          "v."
        ],
        [
          "成为……基础"
        ],
        [
          "based on",
          "ground",
          "root",
          "foundation"
        ],
        ""
      ],
      [
        15,
        "ignore",
        [
          "v."
        ],
        [
          "忽视，不顾"
        ],
        [
          "neglect",
          "overlook",
          "disregard"
        ],
        ""
      ],
      [
        16,
        "fertiliser",
        [
          "n."
        ],
        [
          "化肥，肥料"
        ],
        [
          "chemical",
          "artificial",
          "synthetic",
          "nutrient",
          "fertilizer"
        ],
        ""
      ],
      [
        17,
        "that*",
        [
          "pron."
        ],
        [
          "那；那个"
        ],
        [
          "this",
          "it",
          "they",
          "those",
          "these",
          "such"
        ],
        "*指代是雅思阅读的重要考点，常用于语篇衔接"
      ],
      [
        18,
        "and*",
        [
          "conj."
        ],
        [
          "和，而且"
        ],
        [
          "or",
          "as well as",
          "both…and",
          "not only…but also…",
          "other than",
          "in addition",
          "besides",
          "furthermore",
          "moreover",
          "additionally"
        ],
        "*并列结构是雅思阅读的重要考点，用于连接并列信息"
      ],
      [
        19,
        "rather than*",
        [
          "phr."
        ],
        [
          "而非，不是"
        ],
        [
          "but",
          "yet",
          "however",
          "whereas",
          "nonetheless",
          "nevertheless",
          "although",
          "notwithstanding",
          "though",
          "instead"
        ],
        "*转折结构是雅思阅读的重要考点，用于表达对比关系"
      ],
      [
        20,
        "thanks to*",
        [
          "phr."
        ],
        [
          "由于，幸亏"
        ],
        [
          "stem from",
          "derive",
          "owing to",
          "due to",
          "according to",
          "because of",
          "on account of",
          "as a result of",
          "leading to",
          "because",
          "since",
          "for",
          "in that",
          "as",
          "therefore",
          "hence"
        ],
        "*因果关系是雅思阅读重要考点，用于表达原因和结果"
      ],
      [
        21,
        "phenomenon",
        [
          "n."
        ],
        [
          "现象"
        ],
        [
          "occurrence",
          "event",
          "circumstance",
          "situation",
          "condition"
        ],
        ""
      ],
      [
        22,
        "significant",
        [
          "adj."
        ],
        [
          "重要的，显著的"
        ],
        [
          "important",
          "notable",
          "considerable",
          "substantial",
          "meaningful"
        ],
        ""
      ],
      [
        23,
        "factor",
        [
          "n."
        ],
        [
          "因素"
        ],
        [
          "element",
          "component",
          "aspect",
          "reason",
          "cause"
        ],
        ""
      ],
      [
        24,
        "affect",
        [
          "v."
        ],
        [
          "影响"
        ],
        [
          "influence",
          "impact",
          "alter",
          "change",
          "modify"
        ],
        ""
      ],
      [
        25,
        "benefit",
        [
          "n.",
          "v."
        ],
        [
          "好处，有益于"
        ],
        [
          "advantage",
          "profit",
          "gain",
          "help",
          "assist"
        ],
        ""
      ],
      [
        26,
        "decline",
        [
          "v."
        ],
        [
          "下降，减少"
        ],
        [
          "decrease",
          "reduce",
          "drop",
          "fall",
          "diminish"
        ],
        ""
      ],
      [
        27,
        "increase",
        [
          "v."
        ],
        [
          "增加"
        ],
        [
          "grow",
          "rise",
          "climb",
          "ascend",
          "escalate"
        ],
        ""
      ],
      [
        28,
        "method",
        [
          "n."
        ],
        [
          "方法"
        ],
        [
          "approach",
          "way",
          "technique",
          "strategy",
          "procedure"
        ],
        ""
      ],
      [
        29,
        "theory",
        [
          "n."
        ],
        [
          "理论"
        ],
        [
          "concept",
          "idea",
          "principle",
          "hypothesis"
        ],
        ""
      ],
      [
        30,
        "research",
        [
          "n.",
          "v."
        ],
        [
          "研究"
        ],
        [
          "study",
          "investigation",
          "inquiry",
          "exploration"
        ],
        ""
      ],
      [
        31,
        "data",
        [
          "n."
        ],
        [
          "数据"
        ],
        [
          "information",
          "statistics",
          "figures",
          "evidence"
        ],
        ""
      ],
      [
        32,
        "result",
        [
          "n."
        ],
        [
          "结果"
        ],
        [
          "outcome",
          "consequence",
          "effect",
          "finding"
        ],
        ""
      ],
      [
        33,
        "cause",
        [
          "n.",
          "v."
        ],
        [
          "原因；导致"
        ],
        [
          "reason",
          "source",
          "origin; lead to",
          "bring about"
        ],
        ""
      ],
      [
        34,
        "effect",
        [
          "n.",
          "v."
        ],
        [
          "结果；引起"
        ],
        [
          "consequence",
          "impact",
          "influence; cause",
          "bring about"
        ],
        ""
      ],
      [
        35,
        "percent",
        [
          "n."
        ],
        [
          "百分比"
        ],
        [
          "percentage",
          "proportion",
          "rate",
          "ratio"
        ],
        ""
      ],
      [
        36,
        "amount",
        [
          "n."
        ],
        [
          "数量"
        ],
        [
          "quantity",
          "number",
          "volume",
          "sum"
        ],
        ""
      ],
      [
        37,
        "trend",
        [
          "n."
        ],
        [
          "趋势"
        ],
        [
          "tendency",
          "direction",
          "pattern",
          "movement"
        ],
        ""
      ],
      [
        38,
        "level",
        [
          "n."
        ],
        [
          "水平，级别"
        ],
        [
          "standard",
          "degree",
          "extent",
          "rank"
        ],
        ""
      ],
      [
        39,
        "process",
        [
          "n.",
          "v."
        ],
        [
          "过程；处理"
        ],
        [
          "procedure",
          "method",
          "course; handle",
          "deal with"
        ],
        ""
      ]
    ]
  },
  {
    "title": "第 2 类考点词",
    "define": "当其出现 60% 概率考察",
    "require": "熟记 10 遍以上",
    "description": "重要考点词，需要熟练掌握词义、同义词及在真题中的命题方式。这些词汇在考试中出现频率较高，是提升阅读分数的重要保障。",
    "words": [
      [
        40,
        "diversity",
        [
          "n."
        ],
        [
          "多样性，差异"
        ],
        [
          "variety",
          "difference",
          "variation",
          "plurality",
          "heterogeneity"
        ],
        ""
      ],
      [
        41,
        "detect",
        [
          "v."
        ],
        [
          "查明，发现"
        ],
        [
          "find",
          "look for",
          "seek",
          "search",
          "identify"
        ],
        ""
      ],
      [
        42,
        "isolate",
        [
          "v."
        ],
        [
          "使隔离，使孤立"
        ],
        [
          "separate",
          "insulate",
          "segregate"
        ],
        ""
      ],
      [
        43,
        "avoid",
        [
          "v."
        ],
        [
          "避免"
        ],
        [
          "escape",
          "evade",
          "prevent"
        ],
        ""
      ],
      [
        44,
        "budget",
        [
          "n."
        ],
        [
          "预算"
        ],
        [
          "fund",
          "financial plan",
          "appropriation"
        ],
        ""
      ],
      [
        45,
        "adapt to",
        [
          "phr. v."
        ],
        [
          "使适应"
        ],
        [
          "adjust to",
          "accommodate to",
          "conform to"
        ],
        ""
      ],
      [
        46,
        "alternative",
        [
          "adj.",
          "n."
        ],
        [
          "供替代的，供选择的",
          "替代品"
        ],
        [
          "substitute",
          "option",
          "choice"
        ],
        ""
      ],
      [
        47,
        "compensate",
        [
          "v."
        ],
        [
          "补偿，赔偿"
        ],
        [
          "make up",
          "offset",
          "reimburse"
        ],
        ""
      ],
      [
        48,
        "component",
        [
          "n."
        ],
        [
          "成分，要素"
        ],
        [
          "element",
          "part",
          "ingredient"
        ],
        ""
      ],
      [
        49,
        "military",
        [
          "adj."
        ],
        [
          "军事的"
        ],
        [
          "armed",
          "defense",
          "warfare"
        ],
        ""
      ],
      [
        50,
        "criteria",
        [
          "n."
        ],
        [
          "标准"
        ],
        [
          "standard",
          "criterion",
          "benchmark"
        ],
        ""
      ],
      [
        51,
        "curriculum",
        [
          "n."
        ],
        [
          "课程"
        ],
        [
          "syllabus",
          "course of study",
          "program"
        ],
        ""
      ],
      [
        52,
        "feasible",
        [
          "adj."
        ],
        [
          "可行的"
        ],
        [
          "realistic",
          "viable",
          "practical"
        ],
        ""
      ],
      [
        53,
        "constrain",
        [
          "v."
        ],
        [
          "束缚，限制"
        ],
        [
          "restrict",
          "confine",
          "restrain"
        ],
        ""
      ],
      [
        54,
        "deficiency",
        [
          "n."
        ],
        [
          "缺陷，缺点"
        ],
        [
          "shortage",
          "defect",
          "weakness",
          "inadequacy"
        ],
        ""
      ],
      [
        55,
        "supplement",
        [
          "v."
        ],
        [
          "补充"
        ],
        [
          "add",
          "provide additional",
          "complement"
        ],
        ""
      ],
      [
        56,
        "distinguish",
        [
          "v."
        ],
        [
          "区别，辨别"
        ],
        [
          "differentiate",
          "discriminate",
          "tell apart"
        ],
        ""
      ],
      [
        57,
        "analyze",
        [
          "v."
        ],
        [
          "分析，解释"
        ],
        [
          "examine",
          "diagnose",
          "evaluate",
          "investigate",
          "scrutinize",
          "dissect"
        ],
        ""
      ],
      [
        58,
        "emphasize",
        [
          "v."
        ],
        [
          "强调，着重"
        ],
        [
          "highlight",
          "stress",
          "underscore",
          "accentuate",
          "spotlight",
          "foreground"
        ],
        ""
      ],
      [
        59,
        "enormous",
        [
          "adj."
        ],
        [
          "庞大的，巨大的"
        ],
        [
          "massive",
          "huge",
          "vast",
          "colossal",
          "immense",
          "gigantic"
        ],
        ""
      ],
      [
        60,
        "imitate",
        [
          "v."
        ],
        [
          "模仿"
        ],
        [
          "mimic",
          "copy",
          "replicate"
        ],
        ""
      ],
      [
        61,
        "impair",
        [
          "v."
        ],
        [
          "削弱，减少"
        ],
        [
          "damage",
          "diminish",
          "weaken"
        ],
        ""
      ],
      [
        62,
        "hinder",
        [
          "v."
        ],
        [
          "阻碍"
        ],
        [
          "impede",
          "prevent",
          "obstruct"
        ],
        ""
      ],
      [
        63,
        "legitimate",
        [
          "adj."
        ],
        [
          "合法的"
        ],
        [
          "legal",
          "lawful",
          "valid"
        ],
        ""
      ],
      [
        64,
        "preliminary",
        [
          "adj."
        ],
        [
          "初步的，预备的"
        ],
        [
          "initial",
          "preparatory",
          "introductory",
          "tentative",
          "provisional"
        ],
        ""
      ],
      [
        65,
        "strategy",
        [
          "n."
        ],
        [
          "策略"
        ],
        [
          "plan",
          "approach",
          "tactic",
          "method",
          "scheme"
        ],
        ""
      ],
      [
        66,
        "technology",
        [
          "n."
        ],
        [
          "技术"
        ],
        [
          "technique",
          "skill",
          "craft",
          "engineering"
        ],
        ""
      ],
      [
        67,
        "environment",
        [
          "n."
        ],
        [
          "环境"
        ],
        [
          "surrounding",
          "setting",
          "condition",
          "atmosphere"
        ],
        ""
      ],
      [
        68,
        "population",
        [
          "n."
        ],
        [
          "人口"
        ],
        [
          "people",
          "inhabitants",
          "residents",
          "community"
        ],
        ""
      ],
      [
        69,
        "resource",
        [
          "n."
        ],
        [
          "资源"
        ],
        [
          "asset",
          "material",
          "supply",
          "fund"
        ],
        ""
      ],
      [
        70,
        "limitation",
        [
          "n."
        ],
        [
          "限制"
        ],
        [
          "restriction",
          "constraint",
          "drawback"
        ],
        ""
      ],
      [
        71,
        "convention",
        [
          "n."
        ],
        [
          "手法；习俗"
        ],
        [
          "method; tradition; agreement"
        ],
        ""
      ],
      [
        72,
        "demanding",
        [
          "adj."
        ],
        [
          "苛求的"
        ],
        [
          "challenging",
          "difficult",
          "rigorous"
        ],
        ""
      ],
      [
        73,
        "determine",
        [
          "v."
        ],
        [
          "决定"
        ],
        [
          "decide",
          "establish",
          "ascertain"
        ],
        ""
      ],
      [
        74,
        "accelerate",
        [
          "v."
        ],
        [
          "加速，促进"
        ],
        [
          "speed up",
          "hasten",
          "boost"
        ],
        ""
      ],
      [
        75,
        "ancient",
        [
          "adj."
        ],
        [
          "古代的;古老的"
        ],
        [
          "aged",
          "old",
          "historical"
        ],
        ""
      ],
      [
        76,
        "beneficial",
        [
          "adj."
        ],
        [
          "有益的"
        ],
        [
          "helpful",
          "advantageous",
          "favorable"
        ],
        ""
      ],
      [
        77,
        "chronic",
        [
          "adj."
        ],
        [
          "慢性的，长期性的"
        ],
        [
          "persistent",
          "prolonged",
          "enduring"
        ],
        ""
      ],
      [
        78,
        "conscious",
        [
          "adj."
        ],
        [
          "有意识的，神志清醒的"
        ],
        [
          "aware",
          "knowing",
          "deliberate"
        ],
        ""
      ],
      [
        79,
        "minimize",
        [
          "v."
        ],
        [
          "最小化，使……减少到最少"
        ],
        [
          "reduce",
          "lessen",
          "decrease"
        ],
        ""
      ],
      [
        80,
        "immunity",
        [
          "n."
        ],
        [
          "免疫力"
        ],
        [
          "resistance",
          "protection",
          "defense"
        ],
        ""
      ],
      [
        81,
        "Imperative",
        [
          "adj."
        ],
        [
          "必要的，紧急的"
        ],
        [
          "compelling",
          "necessary",
          "urgent",
          "critical"
        ],
        ""
      ],
      [
        82,
        "secrete",
        [
          "v."
        ],
        [
          "分泌"
        ],
        [
          "discharge",
          "exude",
          "produce"
        ],
        ""
      ],
      [
        83,
        "exaggerate",
        [
          "v."
        ],
        [
          "夸大，夸张"
        ],
        [
          "overstate",
          "magnify",
          "amplify"
        ],
        ""
      ],
      [
        84,
        "transmit",
        [
          "v."
        ],
        [
          "传达，传输"
        ],
        [
          "pass",
          "send",
          "transfer",
          "convey"
        ],
        ""
      ],
      [
        85,
        "extinct",
        [
          "adj."
        ],
        [
          "灭绝的"
        ],
        [
          "die out",
          "vanished",
          "non-existent"
        ],
        ""
      ],
      [
        86,
        "exclusive",
        [
          "adj."
        ],
        [
          "独有的；排外的；专一的"
        ],
        [
          "only",
          "sole",
          "unique"
        ],
        ""
      ],
      [
        87,
        "guarantee",
        [
          "v."
        ],
        [
          "保证，担保"
        ],
        [
          "assure",
          "ensure",
          "warrant"
        ],
        ""
      ],
      [
        88,
        "inherit",
        [
          "v."
        ],
        [
          "继承"
        ],
        [
          "receive",
          "acquire",
          "obtain"
        ],
        ""
      ],
      [
        89,
        "witness",
        [
          "n."
        ],
        [
          "见证，证据；目击者"
        ],
        [
          "view",
          "see",
          "observe"
        ],
        ""
      ],
      [
        90,
        "magnetic",
        [
          "adj."
        ],
        [
          "有磁性的"
        ],
        [
          "attractive",
          "appealing",
          "captivating"
        ],
        ""
      ],
      [
        91,
        "loss",
        [
          "n."
        ],
        [
          "减少；亏损；失败；遗失的"
        ],
        [
          "waste",
          "gone",
          "decline"
        ],
        ""
      ],
      [
        92,
        "option",
        [
          "n."
        ],
        [
          "选择"
        ],
        [
          "choice",
          "alternative",
          "selection"
        ],
        ""
      ],
      [
        93,
        "prefer to",
        [
          "phr. v."
        ],
        [
          "更喜欢"
        ],
        [
          "rather",
          "favor",
          "choose"
        ],
        ""
      ],
      [
        94,
        "priority",
        [
          "n."
        ],
        [
          "优先权"
        ],
        [
          "preference",
          "preferential",
          "precedence"
        ],
        ""
      ],
      [
        95,
        "primary",
        [
          "adj."
        ],
        [
          "主要的"
        ],
        [
          "principal",
          "main",
          "foremost"
        ],
        ""
      ],
      [
        96,
        "principle",
        [
          "n."
        ],
        [
          "原理"
        ],
        [
          "rule",
          "doctrine",
          "fundamental"
        ],
        ""
      ],
      [
        97,
        "potential",
        [
          "n."
        ],
        [
          "潜能",
          "adj.潜在的"
        ],
        [
          "possibility",
          "latent",
          "capability"
        ],
        ""
      ],
      [
        98,
        "quantity",
        [
          "n."
        ],
        [
          "量，数量"
        ],
        [
          "amount",
          "number",
          "volume"
        ],
        ""
      ],
      [
        99,
        "settle",
        [
          "v."
        ],
        [
          "解决；定居，稳定"
        ],
        [
          "resolve",
          "fix",
          "establish"
        ],
        ""
      ],
      [
        100,
        "settle",
        [
          "v."
        ],
        [
          "解决；定居，稳定"
        ],
        [
          "resolve",
          "fix",
          "establish"
        ],
        ""
      ],
      [
        101,
        "sophisticate",
        [
          "v."
        ],
        [
          "使复杂"
        ],
        [
          "complicate",
          "refine",
          "elaborate"
        ],
        ""
      ],
      [
        102,
        "specific",
        [
          "adj."
        ],
        [
          "明确的；特殊的"
        ],
        [
          "detailed",
          "particular",
          "precise"
        ],
        ""
      ],
      [
        103,
        "survive",
        [
          "v."
        ],
        [
          "存活，幸存"
        ],
        [
          "remain",
          "endure",
          "outlive"
        ],
        ""
      ],
      [
        104,
        "swift",
        [
          "adj."
        ],
        [
          "迅速的，敏捷的，立刻的"
        ],
        [
          "quick",
          "rapid",
          "immediate"
        ],
        ""
      ],
      [
        105,
        "unexpectedly",
        [
          "adv."
        ],
        [
          "出乎意料的"
        ],
        [
          "surprising",
          "surprisingly",
          "abruptly"
        ],
        ""
      ],
      [
        106,
        "surrounding",
        [
          "n."
        ],
        [
          "环境"
        ],
        [
          "setting",
          "environment",
          "vicinity"
        ],
        ""
      ],
      [
        107,
        "attempt",
        [
          "n."
        ],
        [
          "试图，尝试"
        ],
        [
          "try",
          "test",
          "endeavor"
        ],
        ""
      ],
      [
        108,
        "expertise",
        [
          "n."
        ],
        [
          "专门技术"
        ],
        [
          "knowledge",
          "skill",
          "proficiency"
        ],
        ""
      ],
      [
        109,
        "faculty",
        [
          "n."
        ],
        [
          "能力，才能；全体教员"
        ],
        [
          "ability",
          "capability",
          "staff"
        ],
        ""
      ],
      [
        110,
        "donate",
        [
          "v."
        ],
        [
          "捐赠"
        ],
        [
          "contribute",
          "give",
          "provide"
        ],
        ""
      ],
      [
        111,
        "dynamics",
        [
          "n."
        ],
        [
          "动力学"
        ],
        [
          "energy",
          "force",
          "momentum"
        ],
        ""
      ],
      [
        112,
        "incentive",
        [
          "n."
        ],
        [
          "刺激,鼓励;动机"
        ],
        [
          "motive",
          "stimulus",
          "encouragement"
        ],
        ""
      ],
      [
        113,
        "mortality",
        [
          "n."
        ],
        [
          "死亡率"
        ],
        [
          "death",
          "fatality",
          "demise"
        ],
        ""
      ],
      [
        114,
        "peripheral",
        [
          "adj."
        ],
        [
          "外围的，次要的"
        ],
        [
          "unimportant",
          "minor",
          "marginal"
        ],
        ""
      ],
      [
        115,
        "vicinity",
        [
          "n."
        ],
        [
          "邻近，附近"
        ],
        [
          "neighbourhood",
          "nearby",
          "proximity"
        ],
        ""
      ],
      [
        116,
        "threaten",
        [
          "v."
        ],
        [
          "威胁，危及"
        ],
        [
          "endanger",
          "jeopardize",
          "risk",
          "hazard",
          "imperil"
        ],
        ""
      ],
      [
        117,
        "practice",
        [
          "n."
        ],
        [
          "实践；练习"
        ],
        [
          "method",
          "exercise",
          "application"
        ],
        ""
      ],
      [
        118,
        "bacteria",
        [
          "n."
        ],
        [
          "细菌"
        ],
        [
          "virus",
          "germ",
          "microbe",
          "pathogen"
        ],
        ""
      ],
      [
        119,
        "be subject to",
        [
          "phr. v."
        ],
        [
          "受…...支配"
        ],
        [
          "face",
          "be exposed to",
          "be prone to"
        ],
        ""
      ],
      [
        120,
        "be liable to",
        [
          "phr. v."
        ],
        [
          "易于……"
        ],
        [
          "potential",
          "be likely to",
          "tend to"
        ],
        ""
      ],
      [
        121,
        "innate",
        [
          "adj."
        ],
        [
          "天生的；内在的，直觉的"
        ],
        [
          "built-in",
          "inborn",
          "inherent"
        ],
        ""
      ],
      [
        122,
        "pattern",
        [
          "n."
        ],
        [
          "模式"
        ],
        [
          "formation",
          "model",
          "structure"
        ],
        ""
      ],
      [
        123,
        "therapy",
        [
          "n."
        ],
        [
          "治疗，理疗"
        ],
        [
          "treatment",
          "healing",
          "rehabilitation"
        ],
        ""
      ],
      [
        124,
        "original",
        [
          "adj."
        ],
        [
          "原始的,最初的"
        ],
        [
          "initial",
          "first",
          "primary"
        ],
        ""
      ],
      [
        125,
        "confidential",
        [
          "adj."
        ],
        [
          "机密的,秘密的"
        ],
        [
          "undisclosed",
          "secret",
          "hidden",
          "private"
        ],
        ""
      ],
      [
        126,
        "cognitive",
        [
          "adj."
        ],
        [
          "认知的"
        ],
        [
          "mental",
          "intellectual",
          "perceptual"
        ],
        ""
      ],
      [
        127,
        "comply with",
        [
          "phr. v."
        ],
        [
          "照做，遵守"
        ],
        [
          "obey",
          "adhere to",
          "conform to"
        ],
        ""
      ],
      [
        128,
        "consult",
        [
          "v."
        ],
        [
          "查阅,商量,请教,咨询"
        ],
        [
          "ask for advice",
          "refer to",
          "seek guidance"
        ],
        ""
      ],
      [
        129,
        "superior",
        [
          "adj."
        ],
        [
          "上级的;优秀的"
        ],
        [
          "higher",
          "upper",
          "better"
        ],
        ""
      ],
      [
        130,
        "co-operation",
        [
          "n."
        ],
        [
          "合作，协作"
        ],
        [
          "support",
          "work together",
          "collaboration"
        ],
        ""
      ],
      [
        131,
        "co-ordinate",
        [
          "v."
        ],
        [
          "使……协调"
        ],
        [
          "organize",
          "harmonize",
          "synchronize"
        ],
        ""
      ],
      [
        132,
        "differ",
        [
          "v."
        ],
        [
          "使……相异；使……不同"
        ],
        [
          "vary",
          "contrast",
          "diverge"
        ],
        ""
      ],
      [
        133,
        "cue",
        [
          "n."
        ],
        [
          "线索"
        ],
        [
          "hint",
          "clue",
          "signal"
        ],
        ""
      ],
      [
        134,
        "signal",
        [
          "n."
        ],
        [
          "信号"
        ],
        [
          "symbol",
          "mark",
          "sign",
          "indication"
        ],
        ""
      ],
      [
        135,
        "abandon",
        [
          "v."
        ],
        [
          "放弃，遗弃"
        ],
        [
          "quit",
          "give up",
          "forsake",
          "desert"
        ],
        ""
      ],
      [
        136,
        "halt",
        [
          "n."
        ],
        [
          "停止"
        ],
        [
          "stop",
          "quit",
          "cease"
        ],
        ""
      ],
      [
        137,
        "fragile",
        [
          "adj."
        ],
        [
          "脆弱的"
        ],
        [
          "vulnerable",
          "delicate",
          "breakable"
        ],
        ""
      ],
      [
        138,
        "retain",
        [
          "v."
        ],
        [
          "记住"
        ],
        [
          "maintain",
          "preserve",
          "keep"
        ],
        ""
      ],
      [
        139,
        "vanish",
        [
          "v."
        ],
        [
          "消失，绝迹"
        ],
        [
          "disappear",
          "fade",
          "evaporate"
        ],
        ""
      ],
      [
        140,
        "delivery",
        [
          "n."
        ],
        [
          "递送"
        ],
        [
          "dispatch",
          "shipment",
          "distribution"
        ],
        ""
      ],
      [
        141,
        "erode",
        [
          "v."
        ],
        [
          "侵蚀"
        ],
        [
          "wear away",
          "corrode",
          "degrade",
          "deteriorate"
        ],
        ""
      ],
      [
        142,
        "induce",
        [
          "v."
        ],
        [
          "引起，引诱"
        ],
        [
          "cause",
          "lead to",
          "trigger"
        ],
        ""
      ],
      [
        143,
        "stable",
        [
          "adj."
        ],
        [
          "稳定的"
        ],
        [
          "constant",
          "unchanged",
          "steady"
        ],
        ""
      ],
      [
        144,
        "integrate",
        [
          "v."
        ],
        [
          "使……成整体"
        ],
        [
          "combine",
          "incorporate",
          "unify"
        ],
        ""
      ],
      [
        145,
        "equal",
        [
          "adj."
        ],
        [
          "平等的; 相等的; 胜任的"
        ],
        [
          "equivalent",
          "matching",
          "capable",
          "adequate"
        ],
        ""
      ],
      [
        146,
        "grant",
        [
          "v."
        ],
        [
          "拨款；授予"
        ],
        [
          "award",
          "provide",
          "approve funding",
          "allocate"
        ],
        ""
      ]
    ]
  },
  {
    "title": "第 3 类考点词",
    "define": "阅读中被考察过的单词，是阅读的考点词",
    "require": "熟记 5 遍以上",
    "description": "次重要考点词，需要掌握词义、同义词及在真题中的命题方式。这些词汇在考试中也有出现，掌握它们有助于进一步提高成绩。",
    "words": [
      [
        147,
        "accumulate",
        [
          "v."
        ],
        [
          "积累，积聚"
        ],
        [
          "gather",
          "amass",
          "collect",
          "build up",
          "accrue",
          "heap up",
          "pile up"
        ],
        ""
      ],
      [
        148,
        "addictive",
        [
          "adj."
        ],
        [
          "上瘾的"
        ],
        [
          "habit-forming",
          "compulsive",
          "obsessive",
          "addictive"
        ],
        ""
      ],
      [
        149,
        "adversity",
        [
          "n."
        ],
        [
          "逆境，不幸"
        ],
        [
          "hardship",
          "misfortune",
          "difficulty",
          "challenges",
          "tribulation"
        ],
        ""
      ],
      [
        150,
        "aggression",
        [
          "n."
        ],
        [
          "侵犯，侵害"
        ],
        [
          "attack",
          "hostility",
          "violence",
          "assault",
          "confrontation",
          "belligerence"
        ],
        ""
      ],
      [
        151,
        "agreeable",
        [
          "adj."
        ],
        [
          "令人愉快的；合适的；和蔼可亲的"
        ],
        [
          "pleasant",
          "enjoyable",
          "favorable",
          "satisfactory",
          "congenial"
        ],
        ""
      ],
      [
        152,
        "aid",
        [
          "n."
        ],
        [
          "援助，帮助"
        ],
        [
          "help",
          "assistance",
          "support",
          "relief",
          "backing",
          "facilitation"
        ],
        ""
      ],
      [
        153,
        "allergic",
        [
          "adj."
        ],
        [
          "过敏的；对……极讨厌的"
        ],
        [
          "sensitive",
          "adverse",
          "hostile",
          "allergic to",
          "反感"
        ],
        ""
      ],
      [
        154,
        "altitude",
        [
          "n."
        ],
        [
          "高度，海拔"
        ],
        [
          "height",
          "elevation",
          "altitude"
        ],
        ""
      ],
      [
        155,
        "application",
        [
          "n."
        ],
        [
          "应用"
        ],
        [
          "utilization",
          "use",
          "implementation"
        ],
        ""
      ],
      [
        156,
        "approve",
        [
          "v."
        ],
        [
          "批准"
        ],
        [
          "agree",
          "authorize",
          "endorse",
          "sanction"
        ],
        ""
      ],
      [
        157,
        "array",
        [
          "n."
        ],
        [
          "排列，大批"
        ],
        [
          "arrangement",
          "order",
          "series"
        ],
        ""
      ],
      [
        158,
        "assign",
        [
          "v."
        ],
        [
          "分配，指派"
        ],
        [
          "allocate",
          "designate",
          "appoint"
        ],
        ""
      ],
      [
        159,
        "association",
        [
          "n."
        ],
        [
          "协会，联盟；联系"
        ],
        [
          "union",
          "connection",
          "relationship"
        ],
        ""
      ],
      [
        160,
        "attitude",
        [
          "n."
        ],
        [
          "看法，态度"
        ],
        [
          "opinion",
          "perspective",
          "viewpoint"
        ],
        ""
      ],
      [
        161,
        "authority",
        [
          "n."
        ],
        [
          "当局，权威"
        ],
        [
          "government",
          "power",
          "expert"
        ],
        ""
      ],
      [
        162,
        "be consistent with",
        [],
        [
          "与……一致"
        ],
        [
          "compatible",
          "align with",
          "correspond to"
        ],
        ""
      ],
      [
        163,
        "bear",
        [
          "v."
        ],
        [
          "承担；忍受"
        ],
        [
          "tolerate",
          "endure",
          "withstand"
        ],
        ""
      ],
      [
        164,
        "blight",
        [
          "v."
        ],
        [
          "使衰败，破坏（尤指植物或前景）"
        ],
        [
          "damage",
          "ruin",
          "wither",
          "devastate"
        ],
        ""
      ],
      [
        165,
        "boundary",
        [
          "n."
        ],
        [
          "边界；底线"
        ],
        [
          "barrier",
          "limit",
          "border"
        ],
        ""
      ],
      [
        166,
        "bungle",
        [
          "v."
        ],
        [
          "搞糟，拙劣地工作"
        ],
        [
          "mishandle",
          "botch",
          "mismanage"
        ],
        ""
      ],
      [
        167,
        "burden",
        [
          "n."
        ],
        [
          "负担"
        ],
        [
          "load",
          "weight",
          "responsibility"
        ],
        ""
      ],
      [
        168,
        "calamity",
        [
          "n."
        ],
        [
          "灾难"
        ],
        [
          "disaster",
          "tragedy",
          "catastrophe"
        ],
        ""
      ],
      [
        169,
        "capacity",
        [
          "n."
        ],
        [
          "容量"
        ],
        [
          "volume",
          "ability",
          "capability"
        ],
        ""
      ],
      [
        170,
        "catastrophic",
        [
          "adj."
        ],
        [
          "灾难的"
        ],
        [
          "disastrous",
          "calamitous",
          "ruinous"
        ],
        ""
      ],
      [
        171,
        "cater",
        [
          "v."
        ],
        [
          "迎合；满足需求"
        ],
        [
          "serve",
          "accommodate",
          "satisfy"
        ],
        ""
      ],
      [
        172,
        "certify",
        [
          "v."
        ],
        [
          "证明，保证"
        ],
        [
          "verify",
          "validate",
          "confirm"
        ],
        ""
      ],
      [
        173,
        "civic",
        [
          "adj."
        ],
        [
          "公民的，市政的"
        ],
        [
          "municipal",
          "civil",
          "public"
        ],
        ""
      ],
      [
        174,
        "comment",
        [
          "n.",
          "v."
        ],
        [
          "评论；意见",
          "评论"
        ],
        [
          "remark",
          "opinion",
          "statement"
        ],
        ""
      ],
      [
        175,
        "commitment",
        [
          "n."
        ],
        [
          "承诺，许诺，义务；致力"
        ],
        [
          "engagement",
          "dedication",
          "pledge"
        ],
        ""
      ],
      [
        176,
        "communal",
        [
          "adj."
        ],
        [
          "公共的，公社的"
        ],
        [
          "public",
          "shared",
          "collective"
        ],
        ""
      ],
      [
        177,
        "commute",
        [
          "v."
        ],
        [
          "通勤；用……交换"
        ],
        [
          "travel",
          "exchange"
        ],
        ""
      ],
      [
        178,
        "compare",
        [
          "v."
        ],
        [
          "与……相比较"
        ],
        [
          "contrast",
          "evaluate",
          "assess"
        ],
        ""
      ],
      [
        179,
        "conceal",
        [
          "v."
        ],
        [
          "隐藏；隐瞒"
        ],
        [
          "hide",
          "cover up",
          "disguise"
        ],
        ""
      ],
      [
        180,
        "concentrate",
        [
          "v."
        ],
        [
          "专心于；集中"
        ],
        [
          "focus",
          "center",
          "direct"
        ],
        ""
      ],
      [
        181,
        "concur",
        [
          "v."
        ],
        [
          "同意"
        ],
        [
          "agree",
          "consent",
          "approve"
        ],
        ""
      ],
      [
        182,
        "confer",
        [
          "v."
        ],
        [
          "授予，给予"
        ],
        [
          "grant",
          "bestow",
          "present"
        ],
        ""
      ],
      [
        183,
        "conflict",
        [
          "n."
        ],
        [
          "冲突，矛盾"
        ],
        [
          "disagreement",
          "dispute",
          "clash"
        ],
        ""
      ],
      [
        184,
        "confuse",
        [
          "v."
        ],
        [
          "使混乱，使迷惑"
        ],
        [
          "puzzle",
          "bewilder",
          "perplex"
        ],
        ""
      ],
      [
        185,
        "conservative",
        [
          "adj."
        ],
        [
          "保守的"
        ],
        [
          "traditional",
          "cautious",
          "conventional"
        ],
        ""
      ],
      [
        186,
        "considerable",
        [
          "adj."
        ],
        [
          "相当大的，重要的"
        ],
        [
          "significant",
          "substantial",
          "notable"
        ],
        ""
      ],
      [
        187,
        "contingent",
        [
          "adj."
        ],
        [
          "因情况而异的"
        ],
        [
          "uncertain",
          "dependent",
          "conditional"
        ],
        ""
      ],
      [
        188,
        "controversial",
        [
          "adj."
        ],
        [
          "有争论的"
        ],
        [
          "disputable",
          "debatable",
          "contentious"
        ],
        ""
      ],
      [
        189,
        "correlation",
        [
          "n."
        ],
        [
          "相关，关联"
        ],
        [
          "link",
          "connection",
          "relationship"
        ],
        ""
      ],
      [
        190,
        "courtship",
        [
          "n."
        ],
        [
          "求爱（时期）"
        ],
        [
          "mating",
          "romance",
          "wooing"
        ],
        ""
      ],
      [
        191,
        "crash",
        [
          "n."
        ],
        [
          "碰撞"
        ],
        [
          "collision",
          "impact",
          "wreck"
        ],
        ""
      ],
      [
        192,
        "credibility",
        [
          "n."
        ],
        [
          "可信性"
        ],
        [
          "reliance",
          "trustworthiness",
          "believability"
        ],
        ""
      ],
      [
        193,
        "criminal",
        [
          "n."
        ],
        [
          "罪犯，犯罪者"
        ],
        [
          "offender",
          "delinquent",
          "lawbreaker"
        ],
        ""
      ],
      [
        194,
        "crisis",
        [
          "n."
        ],
        [
          "危机"
        ],
        [
          "emergency",
          "predicament",
          "dilemma"
        ],
        ""
      ],
      [
        195,
        "criticism",
        [
          "n."
        ],
        [
          "批评；指责"
        ],
        [
          "critique",
          "disapproval",
          "condemnation"
        ],
        ""
      ],
      [
        196,
        "curb",
        [
          "v."
        ],
        [
          "限制，抑制"
        ],
        [
          "restrict",
          "control",
          "check"
        ],
        ""
      ],
      [
        197,
        "damp",
        [
          "adj."
        ],
        [
          "潮湿的"
        ],
        [
          "wet",
          "moist",
          "humid"
        ],
        ""
      ],
      [
        198,
        "dazzle",
        [
          "v."
        ],
        [
          "使目眩；使……眼花"
        ],
        [
          "flash",
          "blind",
          "stun"
        ],
        ""
      ],
      [
        199,
        "deadline",
        [
          "n."
        ],
        [
          "最后期限"
        ],
        [
          "limit",
          "cutoff",
          "due date"
        ],
        ""
      ],
      [
        200,
        "delay",
        [
          "n."
        ],
        [
          "延期，耽搁"
        ],
        [
          "postpone",
          "defer",
          "procrastinate"
        ],
        ""
      ],
      [
        201,
        "democratic",
        [
          "adj."
        ],
        [
          "民主的"
        ],
        [
          "participatory",
          "egalitarian",
          "representative"
        ],
        ""
      ],
      [
        202,
        "demographic",
        [
          "adj."
        ],
        [
          "人口统计学的；人口学"
        ],
        [
          "population statistic",
          "statistical",
          "population-based"
        ],
        ""
      ],
      [
        203,
        "dental",
        [
          "adj."
        ],
        [
          "牙科的，牙齿的"
        ],
        [
          "teeth",
          "oral",
          "tooth-related"
        ],
        ""
      ],
      [
        204,
        "depression",
        [
          "n."
        ],
        [
          "抑郁，沮丧"
        ],
        [
          "frustration",
          "sadness",
          "melancholy"
        ],
        ""
      ],
      [
        205,
        "designate",
        [
          "v."
        ],
        [
          "指定；指派，标出"
        ],
        [
          "appoint",
          "assign",
          "mark",
          "identify"
        ],
        ""
      ],
      [
        206,
        "detain",
        [
          "v."
        ],
        [
          "留住"
        ],
        [
          "hold",
          "keep",
          "confine"
        ],
        ""
      ],
      [
        207,
        "devastate",
        [
          "v."
        ],
        [
          "毁坏，毁灭"
        ],
        [
          "wreck",
          "destroy",
          "ruin"
        ],
        ""
      ],
      [
        208,
        "disclose",
        [
          "v."
        ],
        [
          "公开；揭露"
        ],
        [
          "expose",
          "reveal",
          "unveil"
        ],
        ""
      ],
      [
        209,
        "disparate",
        [
          "adj."
        ],
        [
          "不同的"
        ],
        [
          "different",
          "distinct",
          "divergent"
        ],
        ""
      ],
      [
        210,
        "display",
        [
          "n."
        ],
        [
          "显示"
        ],
        [
          "show",
          "exhibit",
          "present"
        ],
        ""
      ],
      [
        211,
        "disrupt",
        [
          "v."
        ],
        [
          "破坏"
        ],
        [
          "destroy",
          "interrupt",
          "disturb"
        ],
        ""
      ],
      [
        212,
        "distract",
        [
          "v."
        ],
        [
          "转移，分心"
        ],
        [
          "divert",
          "divert attention",
          "sidetrack"
        ],
        ""
      ],
      [
        213,
        "distribute",
        [
          "v."
        ],
        [
          "分配，分发"
        ],
        [
          "spread",
          "disperse",
          "allocate"
        ],
        ""
      ],
      [
        214,
        "documentation",
        [
          "n."
        ],
        [
          "文件；文献"
        ],
        [
          "record",
          "papers",
          "materials"
        ],
        ""
      ],
      [
        215,
        "domain",
        [
          "n."
        ],
        [
          "领域"
        ],
        [
          "field",
          "area",
          "sphere"
        ],
        ""
      ],
      [
        216,
        "dominant",
        [
          "adj."
        ],
        [
          "占优势的，占支配地位的"
        ],
        [
          "overbearing",
          "prevailing",
          "predominant"
        ],
        ""
      ],
      [
        217,
        "dramatic",
        [
          "adj."
        ],
        [
          "戏剧化的；激动人心的，引人注意的"
        ],
        [
          "striking",
          "sensational",
          "impressive"
        ],
        ""
      ],
      [
        218,
        "drought",
        [
          "n."
        ],
        [
          "干旱"
        ],
        [
          "dry",
          "aridity",
          "water shortage"
        ],
        ""
      ],
      [
        219,
        "durable",
        [
          "adj."
        ],
        [
          "持久的"
        ],
        [
          "lasting",
          "long-lasting",
          "robust"
        ],
        ""
      ],
      [
        220,
        "eco-friendly",
        [
          "adj."
        ],
        [
          "生态友好的，环保的"
        ],
        [
          "environmentally-friendly",
          "green",
          "sustainable"
        ],
        ""
      ],
      [
        221,
        "elaborate",
        [
          "v."
        ],
        [
          "详细阐述，详细叙述"
        ],
        [
          "illustrate",
          "explain",
          "detail"
        ],
        ""
      ],
      [
        222,
        "elderly",
        [
          "adj."
        ],
        [
          "高龄的"
        ],
        [
          "aged",
          "senior",
          "old"
        ],
        ""
      ],
      [
        223,
        "eliminate",
        [
          "v."
        ],
        [
          "消除，排除"
        ],
        [
          "dispose",
          "remove",
          "eradicate"
        ],
        ""
      ],
      [
        224,
        "elusive",
        [
          "adj."
        ],
        [
          "难懂的，难捉摸的；行踪隐秘的"
        ],
        [
          "hard",
          "evasive",
          "slippery"
        ],
        ""
      ],
      [
        225,
        "encyclopaedia",
        [
          "n."
        ],
        [
          "百科全书"
        ],
        [
          "entire range of knowledge",
          "reference book",
          "compendium"
        ],
        ""
      ],
      [
        226,
        "entrepreneur",
        [
          "n."
        ],
        [
          "企业家"
        ],
        [
          "boss",
          "businessperson",
          "founder"
        ],
        ""
      ],
      [
        227,
        "equator",
        [
          "n."
        ],
        [
          "赤道"
        ],
        [
          "geography",
          "equatorial line",
          "midline"
        ],
        ""
      ],
      [
        228,
        "erratically",
        [
          "adv."
        ],
        [
          "不定的，无视规律地"
        ],
        [
          "unpredictably",
          "irregularly",
          "randomly"
        ],
        ""
      ],
      [
        229,
        "established",
        [
          "adj."
        ],
        [
          "确定的；已制定的，已建立的"
        ],
        [
          "built",
          "confirmed",
          "recognized"
        ],
        ""
      ],
      [
        230,
        "estate",
        [
          "n."
        ],
        [
          "房地产"
        ],
        [
          "property",
          "real estate",
          "land"
        ],
        ""
      ],
      [
        231,
        "ethical",
        [
          "adj."
        ],
        [
          "道德的"
        ],
        [
          "moral",
          "virtuous",
          "principled"
        ],
        ""
      ],
      [
        232,
        "eventually",
        [
          "adv."
        ],
        [
          "最后，终于"
        ],
        [
          "finally",
          "ultimately",
          "in the end"
        ],
        ""
      ],
      [
        233,
        "evidence",
        [
          "n."
        ],
        [
          "迹象；证据"
        ],
        [
          "proof",
          "indication",
          "testimony"
        ],
        ""
      ],
      [
        234,
        "evolve",
        [
          "v."
        ],
        [
          "进化，发展；逐渐形成"
        ],
        [
          "develop",
          "progress",
          "transform"
        ],
        ""
      ],
      [
        235,
        "exhausted",
        [
          "adj."
        ],
        [
          "疲惫的，耗尽的"
        ],
        [
          "fatigue",
          "tired",
          "drained"
        ],
        ""
      ],
      [
        236,
        "experiment",
        [
          "n."
        ],
        [
          "试验，试验"
        ],
        [
          "test",
          "trial",
          "study"
        ],
        ""
      ],
      [
        237,
        "exceptional",
        [
          "adj."
        ],
        [
          "异常的，特别出色的"
        ],
        [
          "extreme",
          "utmost",
          "extraordinary"
        ],
        ""
      ],
      [
        238,
        "explicit",
        [
          "adj."
        ],
        [
          "明确的"
        ],
        [
          "clear",
          "definite",
          "unambiguous"
        ],
        ""
      ],
      [
        239,
        "exploit",
        [
          "v."
        ],
        [
          "开发，利用"
        ],
        [
          "use",
          "harness",
          "utilize"
        ],
        ""
      ],
      [
        240,
        "extend",
        [
          "v."
        ],
        [
          "扩展，延伸，推广"
        ],
        [
          "expand",
          "prolong",
          "stretch"
        ],
        ""
      ],
      [
        241,
        "extract",
        [
          "n.",
          "v."
        ],
        [
          "摘录",
          "提取"
        ],
        [
          "quotation",
          "excerpt",
          "pull out"
        ],
        ""
      ],
      [
        242,
        "famine",
        [
          "n."
        ],
        [
          "饥荒"
        ],
        [
          "hunger",
          "starvation",
          "food shortage"
        ],
        ""
      ],
      [
        243,
        "finite",
        [
          "adj."
        ],
        [
          "有限的"
        ],
        [
          "limited",
          "bounded",
          "restricted"
        ],
        ""
      ],
      [
        244,
        "fitness",
        [
          "n."
        ],
        [
          "健康状况，体能"
        ],
        [
          "physical condition",
          "health",
          "wellness"
        ],
        ""
      ],
      [
        245,
        "foe",
        [
          "n."
        ],
        [
          "敌人，危害物"
        ],
        [
          "enemy",
          "adversary",
          "opponent"
        ],
        ""
      ],
      [
        246,
        "format",
        [
          "n."
        ],
        [
          "格式"
        ],
        [
          "structure",
          "layout",
          "arrangement"
        ],
        ""
      ],
      [
        247,
        "fragment",
        [
          "n."
        ],
        [
          "碎片"
        ],
        [
          "piece",
          "shard",
          "chip"
        ],
        ""
      ],
      [
        248,
        "freeze",
        [
          "n."
        ],
        [
          "冰冻，冻结"
        ],
        [
          "chill",
          "solidify",
          "congeal"
        ],
        ""
      ],
      [
        249,
        "fulfill",
        [
          "v."
        ],
        [
          "满足，实现"
        ],
        [
          "execute",
          "accomplish",
          "achieve"
        ],
        ""
      ],
      [
        250,
        "gene",
        [
          "n."
        ],
        [
          "基因"
        ],
        [
          "factor",
          "hereditary unit",
          "DNA segment"
        ],
        ""
      ],
      [
        251,
        "gifted",
        [
          "adj."
        ],
        [
          "有天赋的，有才华的"
        ],
        [
          "talented",
          "skilled",
          "proficient"
        ],
        ""
      ],
      [
        252,
        "graphic",
        [
          "adj."
        ],
        [
          "形象的；图解的"
        ],
        [
          "picture",
          "visual",
          "illustrated"
        ],
        ""
      ],
      [
        253,
        "habitat",
        [
          "n."
        ],
        [
          "栖息地，住所"
        ],
        [
          "residence",
          "dwelling",
          "environment"
        ],
        ""
      ],
      [
        254,
        "harbor",
        [
          "v.",
          "n."
        ],
        [
          "怀有",
          "海港"
        ],
        [
          "hold",
          "shelter",
          "port"
        ],
        ""
      ],
      [
        255,
        "hardship",
        [
          "n."
        ],
        [
          "困苦；苦难"
        ],
        [
          "difficult",
          "adversity",
          "difficulty"
        ],
        ""
      ],
      [
        256,
        "harsh",
        [
          "adj."
        ],
        [
          "艰难的；严酷的"
        ],
        [
          "rough",
          "severe",
          "brutal"
        ],
        ""
      ],
      [
        257,
        "hypothesis",
        [
          "n."
        ],
        [
          "假设"
        ],
        [
          "assumption",
          "theory",
          "conjecture"
        ],
        ""
      ],
      [
        258,
        "impact",
        [
          "n."
        ],
        [
          "影响"
        ],
        [
          "influence",
          "effect",
          "consequence"
        ],
        ""
      ],
      [
        259,
        "impressive",
        [
          "adj."
        ],
        [
          "感人的；给人深刻印象的"
        ],
        [
          "touching",
          "striking",
          "remarkable"
        ],
        ""
      ],
      [
        260,
        "in accordance with",
        [],
        [
          "依照；与……一致"
        ],
        [
          "conform",
          "comply with",
          "consistent with"
        ],
        ""
      ],
      [
        261,
        "inaccurate",
        [
          "adj."
        ],
        [
          "错误的"
        ],
        [
          "incorrect",
          "wrong",
          "imprecise"
        ],
        ""
      ],
      [
        262,
        "inactive",
        [
          "adj."
        ],
        [
          "不活跃的，不活动的"
        ],
        [
          "passive",
          "idle",
          "dormant"
        ],
        ""
      ],
      [
        263,
        "inappropriate",
        [
          "adj."
        ],
        [
          "不适当的"
        ],
        [
          "hard",
          "unsuitable",
          "improper"
        ],
        ""
      ],
      [
        264,
        "indulge",
        [
          "v."
        ],
        [
          "沉溺（于）"
        ],
        [
          "spoil",
          "pamper",
          "gratify"
        ],
        ""
      ],
      [
        265,
        "infest",
        [
          "v."
        ],
        [
          "侵害；寄生于"
        ],
        [
          "plague",
          "overrun",
          "invade"
        ],
        ""
      ],
      [
        266,
        "installment",
        [
          "n."
        ],
        [
          "分期付款"
        ],
        [
          "regular/periodic payment",
          "分期款项",
          "payment plan"
        ],
        ""
      ],
      [
        267,
        "intelligence",
        [
          "n."
        ],
        [
          "智力"
        ],
        [
          "mind",
          "intellect",
          "cognitive ability"
        ],
        ""
      ],
      [
        268,
        "intense",
        [
          "adj."
        ],
        [
          "强烈的；紧张的；热情的"
        ],
        [
          "strong",
          "vigorous",
          "passionate"
        ],
        ""
      ],
      [
        269,
        "interaction",
        [
          "n."
        ],
        [
          "相互作用，交流互动"
        ],
        [
          "social activities",
          "communication",
          "exchange"
        ],
        ""
      ],
      [
        270,
        "interference",
        [
          "n."
        ],
        [
          "干涉，干扰"
        ],
        [
          "interposition",
          "disruption",
          "obstruction"
        ],
        ""
      ],
      [
        271,
        "interior",
        [
          "n.",
          "adj."
        ],
        [
          "内部",
          "内部的"
        ],
        [
          "inner",
          "internal",
          "inside"
        ],
        ""
      ],
      [
        272,
        "interrupt",
        [
          "v."
        ],
        [
          "中断"
        ],
        [
          "stop",
          "disrupt",
          "halt"
        ],
        ""
      ],
      [
        273,
        "introverted",
        [
          "adj."
        ],
        [
          "内向的"
        ],
        [
          "reserved",
          "inward-looking",
          "shy"
        ],
        ""
      ],
      [
        274,
        "involve",
        [
          "v."
        ],
        [
          "包含，牵涉"
        ],
        [
          "associate",
          "include",
          "encompass"
        ],
        ""
      ],
      [
        275,
        "keen",
        [
          "adj."
        ],
        [
          "热切的；强烈的"
        ],
        [
          "eager",
          "enthusiastic",
          "intense"
        ],
        ""
      ],
      [
        276,
        "label",
        [
          "v."
        ],
        [
          "打上标签"
        ],
        [
          "display",
          "tag",
          "mark"
        ],
        ""
      ],
      [
        277,
        "lack",
        [
          "v."
        ],
        [
          "缺乏；不足"
        ],
        [
          "shortage",
          "deficiency",
          "absence"
        ],
        ""
      ],
      [
        278,
        "landscape",
        [
          "n."
        ],
        [
          "风景"
        ],
        [
          "scene",
          "scenery",
          "view"
        ],
        ""
      ],
      [
        279,
        "likelihood",
        [
          "n."
        ],
        [
          "可能性"
        ],
        [
          "chance",
          "probability",
          "possibility"
        ],
        ""
      ],
      [
        280,
        "limb",
        [
          "n."
        ],
        [
          "四肢"
        ],
        [
          "arm or leg",
          "extremity",
          "appendage"
        ],
        ""
      ],
      [
        281,
        "linguistic",
        [
          "adj."
        ],
        [
          "语言(学)的"
        ],
        [
          "language",
          "verbal",
          "phonetic"
        ],
        ""
      ],
      [
        282,
        "log",
        [
          "v.",
          "n."
        ],
        [
          "记录；日志",
          "原木"
        ],
        [
          "record",
          "logging",
          "journal"
        ],
        ""
      ],
      [
        283,
        "look-in",
        [
          "n."
        ],
        [
          "informal•British",
          "成功的机会"
        ],
        [
          "opportunity",
          "chance",
          "prospect"
        ],
        ""
      ],
      [
        284,
        "lopsided",
        [
          "adj."
        ],
        [
          "不平衡的"
        ],
        [
          "uneven",
          "asymmetrical",
          "skewed"
        ],
        ""
      ],
      [
        285,
        "mainly",
        [
          "adv."
        ],
        [
          "主要的，大体"
        ],
        [
          "primarily",
          "largely",
          "mostly"
        ],
        ""
      ],
      [
        286,
        "malfunction",
        [
          "v."
        ],
        [
          "发生故障;不起作用"
        ],
        [
          "breakdown",
          "fail",
          "misfire"
        ],
        ""
      ],
      [
        287,
        "mammal",
        [
          "n."
        ],
        [
          "哺乳动物"
        ],
        [
          "creature",
          "animal",
          "vertebrate"
        ],
        ""
      ],
      [
        288,
        "manage to do",
        [],
        [
          "设法完成某事"
        ],
        [
          "success",
          "accomplish",
          "achieve"
        ],
        ""
      ],
      [
        289,
        "manifest",
        [
          "v."
        ],
        [
          "出现，表现"
        ],
        [
          "obvious",
          "show",
          "display"
        ],
        ""
      ],
      [
        290,
        "manufacture",
        [
          "n."
        ],
        [
          "生产"
        ],
        [
          "produce",
          "fabrication",
          "creation"
        ],
        ""
      ],
      [
        291,
        "marine",
        [
          "adj."
        ],
        [
          "海产的；航海的；海运的"
        ],
        [
          "sea",
          "oceanic",
          "nautical"
        ],
        ""
      ],
      [
        292,
        "mate",
        [
          "n."
        ],
        [
          "配偶，伴侣"
        ],
        [
          "partner",
          "spouse",
          "companion"
        ],
        ""
      ],
      [
        293,
        "mechanism",
        [
          "n."
        ],
        [
          "机制，原理"
        ],
        [
          "method",
          "process",
          "system"
        ],
        ""
      ],
      [
        294,
        "mental",
        [
          "adj."
        ],
        [
          "精神的，心理的"
        ],
        [
          "psychological",
          "cognitive",
          "intellectual"
        ],
        ""
      ],
      [
        295,
        "mercury",
        [
          "n."
        ],
        [
          "汞，水银"
        ],
        [
          "liquid metal",
          "quicksilver",
          "Hg"
        ],
        ""
      ],
      [
        296,
        "meteorological",
        [
          "adj."
        ],
        [
          "气象学的"
        ],
        [
          "weather",
          "climatic",
          "atmospheric"
        ],
        ""
      ],
      [
        297,
        "migrate",
        [
          "v."
        ],
        [
          "转移,迁移"
        ],
        [
          "move",
          "relocate",
          "emigrate"
        ],
        ""
      ],
      [
        298,
        "moisture",
        [
          "n."
        ],
        [
          "水分，湿度"
        ],
        [
          "humidity",
          "dampness",
          "wetness"
        ],
        ""
      ],
      [
        299,
        "monitor",
        [
          "v."
        ],
        [
          "监控"
        ],
        [
          "surveillance",
          "observe",
          "track"
        ],
        ""
      ],
      [
        300,
        "motif",
        [
          "n."
        ],
        [
          "主题；图形"
        ],
        [
          "theme",
          "pattern",
          "design"
        ],
        ""
      ],
      [
        301,
        "mould",
        [
          "v."
        ],
        [
          "模压，塑造；塑造成"
        ],
        [
          "form",
          "shape",
          "cast"
        ],
        ""
      ],
      [
        302,
        "native",
        [
          "adj."
        ],
        [
          "本国的，土著的；天然的；天赋的"
        ],
        [
          "original",
          "indigenous",
          "local"
        ],
        ""
      ],
      [
        303,
        "nocturnal",
        [
          "adj."
        ],
        [
          "夜间的,夜间发生的"
        ],
        [
          "night",
          "nighttime",
          "dark"
        ],
        ""
      ],
      [
        304,
        "norm",
        [
          "n."
        ],
        [
          "规范"
        ],
        [
          "regulation",
          "standard",
          "convention"
        ],
        ""
      ],
      [
        305,
        "notoriety",
        [
          "n."
        ],
        [
          "名声"
        ],
        [
          "famous",
          "fame",
          "reputation"
        ],
        ""
      ],
      [
        306,
        "objective",
        [
          "n.",
          "adj."
        ],
        [
          "目标，目的",
          "客观的"
        ],
        [
          "goal",
          "aim",
          "unbiased"
        ],
        ""
      ],
      [
        307,
        "obligation",
        [
          "n."
        ],
        [
          "义务"
        ],
        [
          "responsibility",
          "duty",
          "commitment"
        ],
        ""
      ],
      [
        308,
        "obscure",
        [
          "v."
        ],
        [
          "使模糊不清，晦涩化"
        ],
        [
          "blur",
          "cloud",
          "obscure",
          "conceal"
        ],
        ""
      ],
      [
        309,
        "obtain",
        [
          "v."
        ],
        [
          "获得"
        ],
        [
          "get",
          "acquire",
          "gain"
        ],
        ""
      ],
      [
        310,
        "odd",
        [
          "adj."
        ],
        [
          "古怪的"
        ],
        [
          "strange",
          "unusual",
          "peculiar"
        ],
        ""
      ],
      [
        311,
        "odour",
        [
          "n."
        ],
        [
          "气味"
        ],
        [
          "smell",
          "scent",
          "aroma"
        ],
        ""
      ],
      [
        312,
        "offensive",
        [
          "adj."
        ],
        [
          "冒犯的，无礼的"
        ],
        [
          "hostile",
          "insulting",
          "rude"
        ],
        ""
      ],
      [
        313,
        "official",
        [
          "n.",
          "adj."
        ],
        [
          "官员",
          "官方的"
        ],
        [
          "authority",
          "government",
          "formal"
        ],
        ""
      ],
      [
        314,
        "optimum",
        [
          "n.",
          "adj."
        ],
        [
          "最佳效果",
          "最适宜的"
        ],
        [
          "best",
          "ideal",
          "optimal"
        ],
        ""
      ],
      [
        315,
        "ordinary",
        [
          "adj."
        ],
        [
          "普通的；平凡的；平常的"
        ],
        [
          "common",
          "usual",
          "regular"
        ],
        ""
      ],
      [
        316,
        "organ",
        [
          "n."
        ],
        [
          "器官；机构"
        ],
        [
          "a part of a body",
          "institution",
          "component"
        ],
        ""
      ],
      [
        317,
        "out of the question",
        [],
        [
          "不可能的事"
        ],
        [
          "impossible",
          "not an option",
          "unthinkable"
        ],
        ""
      ],
      [
        318,
        "overcome",
        [
          "v."
        ],
        [
          "克服"
        ],
        [
          "defeat",
          "conquer",
          "surmount"
        ],
        ""
      ],
      [
        319,
        "overtake",
        [
          "v."
        ],
        [
          "赶上"
        ],
        [
          "surpass",
          "exceed",
          "outpace"
        ],
        ""
      ],
      [
        320,
        "paralyse",
        [
          "v."
        ],
        [
          "使麻痹，使瘫痪"
        ],
        [
          "disable",
          "incapacitate",
          "immobilize"
        ],
        ""
      ],
      [
        321,
        "paramount",
        [
          "adj."
        ],
        [
          "最重要的，主要的"
        ],
        [
          "principal",
          "supreme",
          "crucial"
        ],
        ""
      ],
      [
        322,
        "participate",
        [
          "v."
        ],
        [
          "参加"
        ],
        [
          "join",
          "engage",
          "take part"
        ],
        ""
      ],
      [
        323,
        "patient",
        [
          "adj.",
          "n."
        ],
        [
          "有耐心的，能容忍的",
          "病人；患者"
        ],
        [
          "tolerant",
          "calm",
          "ill person",
          "sufferer"
        ],
        ""
      ],
      [
        324,
        "peak",
        [
          "n.",
          "v."
        ],
        [
          "最高峰，顶点",
          "使……达到顶峰"
        ],
        [
          "top",
          "summit",
          "climax"
        ],
        ""
      ],
      [
        325,
        "permit",
        [
          "n.",
          "v."
        ],
        [
          "许可证，执照",
          "许可"
        ],
        [
          "allow",
          "authorize",
          "license"
        ],
        ""
      ],
      [
        326,
        "persuade",
        [
          "v."
        ],
        [
          "说服，劝说"
        ],
        [
          "influence",
          "convince",
          "coax"
        ],
        ""
      ],
      [
        327,
        "pessimistic",
        [
          "adj."
        ],
        [
          "悲观的"
        ],
        [
          "negative",
          "gloomy",
          "cynical"
        ],
        ""
      ],
      [
        328,
        "phase",
        [
          "n."
        ],
        [
          "阶段"
        ],
        [
          "process",
          "stage",
          "period"
        ],
        ""
      ],
      [
        329,
        "physical",
        [
          "adj."
        ],
        [
          "身体上的；物质的"
        ],
        [
          "body",
          "bodily",
          "material"
        ],
        ""
      ],
      [
        330,
        "plagiarise",
        [
          "v."
        ],
        [
          "抄袭"
        ],
        [
          "copy",
          "duplicate",
          "steal"
        ],
        ""
      ],
      [
        331,
        "plenty of",
        [],
        [
          "大量的"
        ],
        [
          "many",
          "abundant",
          "numerous"
        ],
        ""
      ],
      [
        332,
        "plot",
        [
          "v."
        ],
        [
          "密谋"
        ],
        [
          "plan",
          "scheme",
          "conspire"
        ],
        ""
      ],
      [
        333,
        "pose",
        [
          "v."
        ],
        [
          "提出，造成，形成"
        ],
        [
          "cause",
          "create",
          "present"
        ],
        ""
      ],
      [
        334,
        "portable",
        [
          "adj."
        ],
        [
          "可携带的"
        ],
        [
          "conveyable",
          "mobile",
          "transportable"
        ],
        ""
      ],
      [
        335,
        "poverty",
        [
          "n."
        ],
        [
          "贫穷"
        ],
        [
          "poor",
          "destitution",
          "hardship"
        ],
        ""
      ],
      [
        336,
        "praise",
        [
          "n."
        ],
        [
          "赞扬"
        ],
        [
          "commend",
          "acclaim",
          "approbation"
        ],
        ""
      ],
      [
        337,
        "predict",
        [
          "v."
        ],
        [
          "预测，预知"
        ],
        [
          "expect",
          "forecast",
          "anticipate"
        ],
        ""
      ],
      [
        338,
        "pressing",
        [
          "adj."
        ],
        [
          "迫切的"
        ],
        [
          "urgent",
          "critical",
          "imperative"
        ],
        ""
      ],
      [
        339,
        "private",
        [
          "adj."
        ],
        [
          "私人的；私有的；私下的"
        ],
        [
          "personal",
          "confidential",
          "individual"
        ],
        ""
      ],
      [
        340,
        "prohibit",
        [
          "v."
        ],
        [
          "禁止"
        ],
        [
          "forbid",
          "ban",
          "prevent"
        ],
        ""
      ],
      [
        341,
        "prolong",
        [
          "v."
        ],
        [
          "拉长，延长"
        ],
        [
          "extend",
          "lengthen",
          "sustain"
        ],
        ""
      ],
      [
        342,
        "promote",
        [
          "v."
        ],
        [
          "促进，推销"
        ],
        [
          "improve",
          "advance",
          "boost"
        ],
        ""
      ],
      [
        343,
        "prosper",
        [
          "v."
        ],
        [
          "使成功，使繁荣"
        ],
        [
          "success",
          "thrive",
          "flourish"
        ],
        ""
      ],
      [
        344,
        "purify",
        [
          "v."
        ],
        [
          "净化"
        ],
        [
          "clean",
          "cleanse",
          "refine"
        ],
        ""
      ],
      [
        345,
        "qualify",
        [
          "v."
        ],
        [
          "取得资格"
        ],
        [
          "fulfill",
          "meet requirements",
          "be eligible"
        ],
        ""
      ],
      [
        346,
        "radical",
        [
          "adj."
        ],
        [
          "彻底的，根本的"
        ],
        [
          "utmost",
          "extreme",
          "fundamental"
        ],
        ""
      ],
      [
        347,
        "range",
        [
          "n."
        ],
        [
          "范围；幅度"
        ],
        [
          "scope",
          "extent",
          "spectrum"
        ],
        ""
      ],
      [
        348,
        "rare",
        [
          "adj."
        ],
        [
          "稀有的"
        ],
        [
          "unusual",
          "scarce",
          "uncommon"
        ],
        ""
      ],
      [
        349,
        "rate",
        [
          "n.",
          "v."
        ],
        [
          "等级",
          "评估"
        ],
        [
          "rank",
          "measure",
          "evaluate"
        ],
        ""
      ],
      [
        350,
        "react",
        [
          "v."
        ],
        [
          "反应"
        ],
        [
          "respond",
          "reply",
          "react"
        ],
        ""
      ],
      [
        351,
        "recreation",
        [
          "n."
        ],
        [
          "娱乐，消遣"
        ],
        [
          "entertainment",
          "leisure",
          "pastime"
        ],
        ""
      ],
      [
        352,
        "reduction",
        [
          "n."
        ],
        [
          "下降，减少"
        ],
        [
          "decrease",
          "decline",
          "drop"
        ],
        ""
      ],
      [
        353,
        "refer to",
        [],
        [
          "指(的是)，涉及，提及"
        ],
        [
          "talk about",
          "mention",
          "allude to"
        ],
        ""
      ],
      [
        354,
        "rehearsal",
        [
          "n."
        ],
        [
          "排演；预演；练习"
        ],
        [
          "preparation",
          "practice",
          "drill"
        ],
        ""
      ],
      [
        355,
        "reject",
        [
          "v."
        ],
        [
          "拒绝，排斥，丢弃"
        ],
        [
          "exclude",
          "refuse",
          "discard"
        ],
        ""
      ],
      [
        356,
        "relevant",
        [
          "adj."
        ],
        [
          "相关的"
        ],
        [
          "relative",
          "pertinent",
          "applicable"
        ],
        ""
      ],
      [
        357,
        "religious",
        [
          "adj."
        ],
        [
          "宗教的；虔诚的"
        ],
        [
          "sacred",
          "spiritual",
          "devotional"
        ],
        ""
      ],
      [
        358,
        "reluctant",
        [
          "adj."
        ],
        [
          "不情愿的"
        ],
        [
          "unwilling",
          "hesitant",
          "disinclined"
        ],
        ""
      ],
      [
        359,
        "reproduce",
        [
          "v."
        ],
        [
          "繁殖"
        ],
        [
          "breed",
          "propagate",
          "generate"
        ],
        ""
      ],
      [
        360,
        "responsible",
        [
          "adj."
        ],
        [
          "负责的，可靠的；有责任的"
        ],
        [
          "liable",
          "accountable",
          "dependable"
        ],
        ""
      ],
      [
        361,
        "revision",
        [
          "n."
        ],
        [
          "修正"
        ],
        [
          "editing",
          "amendment",
          "modification"
        ],
        ""
      ],
      [
        362,
        "revive",
        [
          "v."
        ],
        [
          "使复苏，恢复"
        ],
        [
          "renaissance",
          "resurrect",
          "rejuvenate"
        ],
        ""
      ],
      [
        363,
        "ruin",
        [
          "v."
        ],
        [
          "毁灭"
        ],
        [
          "destroy",
          "devastate",
          "wreck"
        ],
        ""
      ],
      [
        364,
        "scenic",
        [
          "adj."
        ],
        [
          "风景优美的"
        ],
        [
          "beautiful",
          "picturesque",
          "lovely"
        ],
        ""
      ],
      [
        365,
        "shade",
        [
          "n."
        ],
        [
          "遮阳；阴影"
        ],
        [
          "shelter",
          "shadow",
          "cover"
        ],
        ""
      ],
      [
        366,
        "skepticism",
        [
          "n."
        ],
        [
          "怀疑"
        ],
        [
          "doubt",
          "disbelief",
          "cynicism"
        ],
        ""
      ],
      [
        367,
        "soar",
        [
          "v."
        ],
        [
          "激增"
        ],
        [
          "increase",
          "surge",
          "rocket"
        ],
        ""
      ],
      [
        368,
        "solely",
        [
          "adv."
        ],
        [
          "唯一地"
        ],
        [
          "alone",
          "exclusively",
          "merely"
        ],
        ""
      ],
      [
        369,
        "solicitor",
        [
          "n."
        ],
        [
          "律师"
        ],
        [
          "lawyer",
          "attorney",
          "legal representative"
        ],
        ""
      ],
      [
        370,
        "steer",
        [
          "v."
        ],
        [
          "控制，引导"
        ],
        [
          "manage",
          "guide",
          "direct"
        ],
        ""
      ],
      [
        371,
        "stimulate",
        [
          "v."
        ],
        [
          "刺激，激励"
        ],
        [
          "motivate",
          "encourage",
          "inspire"
        ],
        ""
      ],
      [
        372,
        "stride",
        [
          "n."
        ],
        [
          "进展"
        ],
        [
          "progress",
          "advance",
          "headway"
        ],
        ""
      ],
      [
        373,
        "succumb",
        [
          "vi."
        ],
        [
          "屈服"
        ],
        [
          "yield",
          "surrender",
          "give in"
        ],
        ""
      ],
      [
        374,
        "subdivide",
        [
          "v."
        ],
        [
          "把……细分"
        ],
        [
          "break down",
          "partition",
          "segment"
        ],
        ""
      ],
      [
        375,
        "subtle",
        [
          "adj."
        ],
        [
          "微妙的"
        ],
        [
          "delicate",
          "nuanced",
          "faint"
        ],
        ""
      ],
      [
        376,
        "substance",
        [
          "n."
        ],
        [
          "物质；实质"
        ],
        [
          "matter",
          "material",
          "essence"
        ],
        ""
      ],
      [
        377,
        "sufficiency",
        [
          "n."
        ],
        [
          "足量，充足"
        ],
        [
          "enough",
          "adequacy",
          "plenty"
        ],
        ""
      ],
      [
        378,
        "supersede",
        [
          "v."
        ],
        [
          "取代，代替"
        ],
        [
          "replace",
          "substitute",
          "displace"
        ],
        ""
      ],
      [
        379,
        "suppress",
        [
          "v."
        ],
        [
          "抑制，隐瞒"
        ],
        [
          "hold",
          "restrain",
          "conceal"
        ],
        ""
      ],
      [
        380,
        "supremacy",
        [
          "n."
        ],
        [
          "至高无上，很高的地位"
        ],
        [
          "priority",
          "dominance",
          "preeminence"
        ],
        ""
      ],
      [
        381,
        "suspicious",
        [
          "adj."
        ],
        [
          "可疑的"
        ],
        [
          "odd",
          "doubtful",
          "questionable"
        ],
        ""
      ],
      [
        382,
        "sustainable",
        [
          "adj."
        ],
        [
          "可持续的"
        ],
        [
          "long-term",
          "eco-friendly",
          "renewable"
        ],
        ""
      ],
      [
        383,
        "symptom",
        [
          "n."
        ],
        [
          "症状，征兆"
        ],
        [
          "sign",
          "indication",
          "marker"
        ],
        ""
      ],
      [
        384,
        "tension",
        [
          "n."
        ],
        [
          "紧张，不安"
        ],
        [
          "upset",
          "stress",
          "anxiety"
        ],
        ""
      ],
      [
        385,
        "term",
        [
          "n."
        ],
        [
          "术语"
        ],
        [
          "word",
          "expression",
          "phrase"
        ],
        ""
      ],
      [
        386,
        "throughout",
        [
          "adv."
        ],
        [
          "自始至终，到处；全部"
        ],
        [
          "anywhere",
          "everywhere",
          "completely"
        ],
        ""
      ],
      [
        387,
        "toll",
        [
          "n.",
          "v."
        ],
        [
          "通行费",
          "征收"
        ],
        [
          "charge",
          "fee",
          "cost"
        ],
        ""
      ],
      [
        388,
        "trace",
        [
          "n."
        ],
        [
          "追溯；痕迹"
        ],
        [
          "track",
          "trail",
          "vestige"
        ],
        ""
      ],
      [
        389,
        "transcend",
        [
          "v."
        ],
        [
          "胜过，超越"
        ],
        [
          "excel",
          "surpass",
          "exceed"
        ],
        ""
      ],
      [
        390,
        "transit",
        [
          "n.",
          "v."
        ],
        [
          "运输；经过",
          "运送"
        ],
        [
          "send",
          "transport",
          "convey"
        ],
        ""
      ],
      [
        391,
        "tremendous",
        [
          "adj."
        ],
        [
          "巨大的，惊人的"
        ],
        [
          "vast",
          "enormous",
          "massive"
        ],
        ""
      ],
      [
        392,
        "trigger",
        [
          "n."
        ],
        [
          "触发，引发，引起"
        ],
        [
          "begin",
          "initiate",
          "spark"
        ],
        ""
      ],
      [
        393,
        "tropical",
        [
          "adj."
        ],
        [
          "热带的"
        ],
        [
          "hot",
          "equatorial",
          "humid"
        ],
        ""
      ],
      [
        394,
        "unbiased",
        [
          "adj."
        ],
        [
          "公正的，无偏见的"
        ],
        [
          "fair",
          "impartial",
          "objective"
        ],
        ""
      ],
      [
        395,
        "uniform",
        [
          "adj."
        ],
        [
          "始终如一的"
        ],
        [
          "consistent",
          "identical",
          "standardized"
        ],
        ""
      ],
      [
        396,
        "valuable",
        [
          "adj."
        ],
        [
          "宝贵的，有价值的"
        ],
        [
          "benefit",
          "precious",
          "worthwhile"
        ],
        ""
      ],
      [
        397,
        "versatile",
        [
          "adj."
        ],
        [
          "多功能"
        ],
        [
          "all-around",
          "adaptable",
          "flexible"
        ],
        ""
      ],
      [
        398,
        "view",
        [
          "v."
        ],
        [
          "看"
        ],
        [
          "overlook",
          "observe",
          "examine"
        ],
        ""
      ],
      [
        399,
        "violent",
        [
          "adj."
        ],
        [
          "暴力的；猛烈的"
        ],
        [
          "fierce",
          "aggressive",
          "brutal"
        ],
        ""
      ],
      [
        400,
        "visible",
        [
          "adj."
        ],
        [
          "明显的，看得见的"
        ],
        [
          "see",
          "apparent",
          "observable"
        ],
        ""
      ],
      [
        401,
        "visual",
        [
          "adj."
        ],
        [
          "视觉的"
        ],
        [
          "image",
          "optical",
          "pictorial"
        ],
        ""
      ],
      [
        402,
        "well-being",
        [
          "n."
        ],
        [
          "健康，幸福，福祉"
        ],
        [
          "health",
          "happiness",
          "welfare"
        ],
        ""
      ]
    ]
  }
]